export const ROUTES = {
  home:             '/',
  login:            '/login',
  dashboard:        '/dashboard',
  grades:           '/grades',
  gradebook:        '/gradebook',
  gradebookSubject: (subject: string) => `/gradebook/${subject}`,
  assignments:      '/assignments',
  assignmentsNew:   '/assignments/new',
  assignment:       (id: string) => `/assignments/${id}`,
  announcements:    '/announcements',
  announcementsNew: '/announcements/new',
  billing:          '/billing',
  payments:         '/payments',
  suspensions:      '/suspensions',
  students:         '/students',
  student:          (id: string) => `/students/${id}`,
  reports:          '/reports',
  settings:         '/settings',
  account:          '/account',
  calendar:         '/calendar',
} as const
